# hparams_registry -> config.yaml -> CLI (Command Line Interface)
swad: False # Default로는 False로 되어있는 swad 적용한 결과 얻고 싶으면 command에 `--swad True`로 설정
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 0.3
test_batchsize: 128

# models : resnet50, resnet50_barlowtwins, resnet50_moco, clip_resnet50, clip_vit-b16, swag_regnety_16gf
model: resnet50
feat_layers: stem_block